### ISSUE TITLE
트리메뉴 관련문의

### ISSUE THREAD

**Issue by kimtaeok** [axboot/ax-boot-html#3]
안녕하세요 트리메뉴 문의 드립니다.
아래와 같이 name에 데이터는 보이는데 트리 이미지가 않보이거나 hash 컬럼에 코드 값이 보이지 않으면
어떻게 변경해야 하는지 문의 드립니다. 감사합니다.

------추가한 소스------------------------------------------------------------
{
                   key: "id",
                    label: "ID",
                    width: 80,
                    styleClass: function () {
                        return "ABC";
                    },
                    enableFilter: true,
                    align: "center",
                    editor: {
                        type: "text", disabled: function () {
                            // item, value
                            return false;
                        }
                    }
                },

{key: "name", label: "name", width: 100, align: "left", treeControl: true},

tree: {
                    use: true,
                    indentWidth: 10,
                    arrowWidth: 15,
                    iconWidth: 18,
                    icons: {
                            openedArrow: '<i class="fa fa-caret-down" aria-hidden="true"></i>',
                            collapsedArrow: '<i class="fa fa-caret-right" aria-hidden="true"></i>',
                            groupIcon: '<i class="fa fa-folder-open" aria-hidden="true"></i>',
                            collapsedGroupIcon: '<i class="fa fa-folder" aria-hidden="true"></i>',
                            itemIcon: '<i class="fa fa-circle" aria-hidden="true"></i>'
                           },
            	   columnKeys: {
            	   parentKey: "pid",
            	   selfKey: "id"
           	   }
           	},

 var sampleData = [
            {id: 0, name: "Thomas Jang", price: 1000, amount: null, saleDt: "2016-08-29", customer: "장기영", saleType: "A", isChecked: "Y", __disable_selection__: true},
            {pid: "0", id: "2", name: "Seowoo", price: 1100, amount: 11, saleDt: "2016-08-28", customer: "장서우", saleType: "B", isChecked: "N"},
            {pid: "0", id: "3", name: "Mondo", price: 1200, amount: 10, saleDt: "2016-08-27", customer: "이영희", saleType: "A", isChecked: "N"},
            {pid: "0", id: "4", name: "Brant", price: 1300, amount: 8, saleDt: "2016-08-25", customer: "황인서", saleType: "C", isChecked: "Y"},
            {pid: "4", id: "5", name: "Tiffany", price: 1500, amount: 2, saleDt: "2016-08-26", customer: "이서연", saleType: "A", isChecked: "N"},
            {pid: "4", id: "6", name: "Edward", price: 1400, amount: 5, saleDt: "2016-08-29", customer: "황세진", saleType: "D", isChecked: "Y"},
           {pid: "4", id: "7", name: "Bill", price: 1400, amount: 5, saleDt: "2016-08-29", customer: "이하종", saleType: "B", isChecked: "N"},
            {pid: "0", id: "8", name: "Aeei", price: 1400, amount: 5, saleDt: "2016-08-29", customer: "김혜미", saleType: "C", isChecked: "Y"}
        ];
------추가한 소스------------------------------------------------------------
![20170410_115053](https://cloud.githubusercontent.com/assets/18026051/24844211/01db12bc-1de4-11e7-9983-8c5e0224ee99.jpg)

**Comment by groovedk** [comment]
그리드 컨피그 컬럼정의 하는 부분의 menuNm 에 treeControl: true 속성을 추가하시면 트리 컨트롤이 표현됩니다. 
해쉬코드는 fnObj.gridView01.target.getList() 로 데이터를 확인해보시면  __hs__ 키로 정의되어있습니다. 
```
fnObj.gridView01.target.getList()[0]["__hs__"]
```

**Comment by kimtaeok** [comment]
넵 고맙습니다.
